title: hisaac.net
name: hisaac.net
author: Isaac Halvorson
email: hello@hisaac.net
description: Isaac Halvorson's home on the web
url: "https://hisaac.net"
twitter_username: hisaac
github_username: hisaac

permalink: /:year/:month/:day/:title.html
timezone: America/North_Dakota/Center
strict_front_matter: true
livereload: true

include:
  - .well-known

exclude:
  - CHANGELOG*
  - Gemfile*
  - LICENSE*
  - old
  - README*

keep-files:
  - resume

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: Isaac Halvorson

jekyll_tidy:
  exclude:
    - .well-known/humans.txt
    - .well-known/robots.txt
